server:
    port: ${port:3000}

spring:
    application:
        name: cursoumc

    # config to pretty print json no navegado 
    jackson:
        serialization:
            indent-output: true

    profiles: # prd dev
        active: dev
        default: dev


    # datasource:
    #     driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #     url: jdbc:sqlserver://;serverName=localhost;databaseName=cursouml;encrypt=false
    #     username: sa
    #     password: Xeon123

    # jpa:
    #     show-sql: true
    
    #     hibernate:
    #         ddl-auto: update
    #         # format_sql: true

# essa chave para recriar a estrutura do bd em cada inicializacao
# spring.jpa.hibernate.ddl-auto=create-drop

# controla se executa os scripts de data.sql
# spring.sql.init.mode=never



# spring.sql.init.platform=mssql
# spring.sql.init.data-locations=myscript.sql

# spring.datasource.url=jdbc:sqlserver://;serverName=localhost;databaseName=cursouml;encrypt=true;trustServerCertificate=true;
# spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.datasource.username=SA
# spring.datasource.password=Xeon123
# spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update