spring:

    datasource:
        # in memory 
        # url: jdbc:h2:mem:mydb
        url: jdbc:h2:file:C:\java\database
        username: sa
        password:
        driverClassName: org.h2.Driver

    jpa:
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.H2Dialect
    
        hibernate:
            ddl-auto: create
        
        # spring.jpa.hibernate.ddl-auto=none

    h2:
        console:
            enabled: true

    sql:
        init:
            mode: always



# spring.jpa.